---
# tasks file for jobOne

- name: Copy track file if exists on repo server
  copy:
     src: "{{syncFilePath}}{{dc}}/{{env}}/.TRACK"
     dest: /tmp/aiRelease/.
  ignore_errors: yes
  become: yes
  become_user: root
  become_method: sudo

- name: run script - {{hostvars['localhost']['script_to_run'] }}
  shell: scripts/{{hostvars['localhost']['script_to_run'] }}
  args:
    chdir: /tmp/aiRelease
    executable: /bin/bash
  environment:
    TERM: vt100
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: yes
  register: output

- name: check if track file exists
  stat:
    path: /tmp/aiRelease/.TRACK
  register: isTrackExists

- name: copy the track file to controller
  fetch:
    src: /tmp/aiRelease/.TRACK
    dest: "{{syncFilePath}}{{dc}}/{{env}}/"
    flat: yes
  when: isTrackExists.stat.exists == True
  become: yes
  become_user: root
  become_method: sudo

- name: output
  debug: msg={{output}}
